### ISSUE TITLE
Create an eclipse project for the code for Sriram so he can use JUnit

### ISSUE THREAD

**Issue by amitvakula** [Unit4TechProjects/ChoiceOptimization#15]

**Comment by mmussomele** [comment]
he can't make an eclipse project on his own?

**Comment by amitvakula** [comment]
He doesn't know how to run JUnit for command line so I said to try using
Eclipse to run JUnit. Since Eclipse is kind of hard, I offered to build the
project for him myself since he's been struggling with running the code and
I don't want that to be the reason why he's still stuck...

**Comment by mmussomele** [comment]
Since eclipse is hard, why not just have him practice the command line? If he's going to be studying computer science he'll have to learn it sometime. Honestly the command line is easier to configure than eclipse anyway. And he doesn't even have to run JUnit directly. He just goes to the directory and runs `ant runtests` and it does all the work. 

I mean if you want to make him one go ahead, but I actually don't have eclipse, so I can't.

**Comment by amitvakula** [comment]
hmmm.....good point.

I found a good .gitignore online to untracked all .Eclipse files. why don't
we use that so that you don't have to worry about Eclipse but we can still
develop with Eclipse?

Also bro haven't talked to you in a while. We should Skype!

**Comment by mmussomele** [comment]
Go ahead and add it to the current .gitignore anyway, so we have that safeguard just in case.
